name: mata3im_delivery
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  flutter_bloc:
  flutter_phoenix:
  shared_preferences:
  http: ^0.12.2
  flutter_easyloading: ^2.2.2
  get: ^3.24.0
  geolocator: ^6.1.13
  google_maps_flutter: ^2.0.6
  cached_network_image: ^2.5.0
  socket_io_common_client: ^0.10.0
  flutter_polyline_points: ^0.2.4
  rxdart: ^0.25.0
  sentry_flutter: ^4.0.4
  url_launcher: ^5.7.10
  ffi: ^ 1.0.0
  splashscreen:
  geocoder: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: "^0.8.0"

flutter_launcher_name:
  name: "Mata3im Delivery"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/appIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/Sans/GoogleSans-Bold.ttf
        - asset: fonts/Sans/GoogleSans-Regular.ttf
        - asset: fonts/Sans/GoogleSans-Medium.ttf


