#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/omarbakry/Developer/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/omarbakry/Desktop/codecanyon-ebIo3BF6-food-ordering-app-food-delivery-app-3-apps-android-ios-app-template-flutter-foodish/foodish-delivery-master"
export "FLUTTER_TARGET=/Users/omarbakry/Desktop/codecanyon-ebIo3BF6-food-ordering-app-food-delivery-app-3-apps-android-ios-app-template-flutter-foodish/foodish-delivery-master/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/omarbakry/Developer/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
